/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as SimRouteImport } from './routes/sim'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DirectedGuidesRouteImport } from './routes/directed-guides'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectedGuidesRoute = DirectedGuidesRouteImport.update({
  id: '/directed-guides',
  path: '/directed-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/checklist': typeof ChecklistRoute
  '/directed-guides': typeof DirectedGuidesRoute
  '/download': typeof DownloadRoute
  '/guide': typeof GuideRoute
  '/mods': typeof ModsRoute
  '/setup': typeof SetupRoute
  '/sim': typeof SimRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/checklist': typeof ChecklistRoute
  '/directed-guides': typeof DirectedGuidesRoute
  '/download': typeof DownloadRoute
  '/guide': typeof GuideRoute
  '/mods': typeof ModsRoute
  '/setup': typeof SetupRoute
  '/sim': typeof SimRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/checklist': typeof ChecklistRoute
  '/directed-guides': typeof DirectedGuidesRoute
  '/download': typeof DownloadRoute
  '/guide': typeof GuideRoute
  '/mods': typeof ModsRoute
  '/setup': typeof SetupRoute
  '/sim': typeof SimRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/checklist'
    | '/directed-guides'
    | '/download'
    | '/guide'
    | '/mods'
    | '/setup'
    | '/sim'
    | '/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/checklist'
    | '/directed-guides'
    | '/download'
    | '/guide'
    | '/mods'
    | '/setup'
    | '/sim'
    | '/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/checklist'
    | '/directed-guides'
    | '/download'
    | '/guide'
    | '/mods'
    | '/setup'
    | '/sim'
    | '/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ChecklistRoute: typeof ChecklistRoute
  DirectedGuidesRoute: typeof DirectedGuidesRoute
  DownloadRoute: typeof DownloadRoute
  GuideRoute: typeof GuideRoute
  ModsRoute: typeof ModsRoute
  SetupRoute: typeof SetupRoute
  SimRoute: typeof SimRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directed-guides': {
      id: '/directed-guides'
      path: '/directed-guides'
      fullPath: '/directed-guides'
      preLoaderRoute: typeof DirectedGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ChecklistRoute: ChecklistRoute,
  DirectedGuidesRoute: DirectedGuidesRoute,
  DownloadRoute: DownloadRoute,
  GuideRoute: GuideRoute,
  ModsRoute: ModsRoute,
  SetupRoute: SetupRoute,
  SimRoute: SimRoute,
  TroubleshootingRoute: TroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
